Update changelog for release-v1.5.0
dell/csm pull request #555
Opened 2022-11-23 00:42 UTC by csmbot

Update changelog to include features and bug fixes

2022-11-23 06:09 UTC, baoy1 approved these changes

2022-11-28 10:35 UTC, shanmydell requested changes
All issues are not linked to milestones

2022-11-28 10:42 UTC, shanmydell commented
https://github.com/dell/csm/issues/528 - This issue is missing in changelog

2022-11-28 14:06 UTC, closed without merging

2022-11-28 14:11 UTC, shaynafinocchiaro commented
> #528 - This issue is missing in changelog

@shanmydell Closing this PR. To account for missing Features and Bugs, a new Changelog PR has been created. - https://github.com/dell/csm/pull/564